<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="UK-NOTT-SCRIPT4" name="com.northgateps.cm.smokeTests.TestRunner_ST" tests="1" failures="0" timestamp="27 Mar 2019 09:56:58 GMT" time="789.741" errors="1">
  <testcase name="feature" time="789.741" classname="com.northgateps.cm.smokeTests.TestRunner_ST">
    <error type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: This needs to be set as a Fail">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: This needs to be set as a Fail
	at com.northgateps.cm.platform.api.CustomTestNGCucumberRunner.runCucumber(CustomTestNGCucumberRunner.java:97)
	at com.northgateps.cm.platform.api.CustomAbstractTestNGCucumberTests.feature(CustomAbstractTestNGCucumberTests.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: This needs to be set as a Fail
	at org.testng.Assert.fail(Assert.java:94)
	at com.northgateps.cm.platform.api.ConnectMobilePageHelper.CloseFailedTest(ConnectMobilePageHelper.java:1624)
	at com.northgateps.cm.intel.FTS.IntelFTS01.userHasCompletedAllTheFieldsOnForm(IntelFTS01.java:365)
	at âœ½.And User has completed all the fields on "Vehicle details" form on "Vehicle" card with Link Reason "Subject of"(resources/Features/SmokeTests/Intel_ST.feature:65)
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- com.northgateps.cm.smokeTests.TestRunner_ST -->
